version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/www
    steps:
      - checkout
      # Bundle install dependencies
      - run: bundle install
      - run:
          name: jekyll build
          command: bundle exec jekyll build
      
      - add_ssh_keys:
         fingerprints:
            - "22:77:57:a7:45:96:dd:78:46:ef:b5:e7:4b:93:e5:87"

      - run:
         name: Delopy
         command: |
             echo '150.95.141.52 SHA256:V28nTib5yVUv+xLqU7O1TYDL6vprbl8IDsd8Cb756sY.' >> ~/.ssh/known_hosts 
             scp -oStrictHostKeyChecking=no -r ~//www/_site/* blog_sync@150.95.141.52:/var/www/test.com/public_html/
    

